### PR TITLE
Fix issues with Indexes

### LINKED ISSUE #170: [PE-D] student -dl command, if only the person index is provided ( lesson index not provided), no error shown on application
This is the result when the command is typed and then entered, no visible output from application but console throws errors.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: junwei26/ped#5

### PR DESCRIPTION
**Pull request by tanhuakun**
Fix #170 #175 #158 

Now invalid indexes display "Index provided is invalid, did you ensure that each index is a positive integer and less than 2,147,483,648".

Please merge this asap because many Parser commands were changed.

### CODE REVIEW

File: src/main/java/seedu/address/logic/parser/groups/AddGroupCommandParser.java [hunk 1]
```diff
@@ -39,7 +40,7 @@ public AddGroupCommand parse(String userInput) throws ParseException {
         try {
             indexes = ParserUtil.parseAllIndex(argMultimap.getPreamble());
         } catch (ParseException pe) {
-            throw new ParseException(String.format(MESSAGE_INVALID_COMMAND_FORMAT, MESSAGE_USAGE), pe);
```
Comment (jeremy-7007) [inline src/main/java/seedu/address/logic/parser/groups/AddGroupCommandParser.java:42]: Instead of using only 1 argument for MESSAGE_INVALID_COMMAND_FORMAT, why not add another argument to it? That way, the MESSAGE_USAGE can still be displayed after the index error message. I just think the message usage is quite convenient for the user.

**Review by jeremy-7007 — COMMENTED** [review]
Sorry to bother you more, but there is a way to display both the index error message and the message usage. I've detailed it in the comment.

File: src/main/java/seedu/address/logic/parser/groups/AddGroupCommandParser.java (hunk 1 above)
Comment (jeremy-7007) [reply src/main/java/seedu/address/logic/parser/groups/AddGroupCommandParser.java:42]: So instead of "n\%1$s", you can change it to: "n\%1$s n\%2$s" in MESSAGE_INVALID_COMMAND_FORMAT so that it takes in 2 arguments and display both.

Comment (tanhuakun) [reply src/main/java/seedu/address/logic/parser/groups/AddGroupCommandParser.java:42]: Alternative solution fixed in the new commit. Checks to the length of preamble was done to ensure "invalid index" messages only displayed when the index is at fault.

**Review by jeremy-7007 — APPROVED** [review]
LGTM!
